FROM node:20-alpine
WORKDIR /app
RUN corepack enable && pnpm add -g eas-cli
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps ./apps
COPY packages ./packages
RUN pnpm install --frozen-lockfile
CMD ["pnpm", "dev:player"]
