export const mockProduct = (overrides: Record<string, unknown> = {}) => ({
  id: 'prod-1',
  name: 'Shuttlecock',
  slug: 'shuttlecock',
  description: 'Pro grade',
  sku: 'SHUT-001',
  price: '299',
  compareAtPrice: null,
  costPrice: null,
  stock: 50,
  lowStockThreshold: 5,
  isActive: true,
  isFeatured: false,
  averageRating: null,
  categoryId: 'cat-1',
  sportId: null,
  deletedAt: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  category: { id: 'cat-1', name: 'Gear', slug: 'gear', description: null, imageUrl: null, sortOrder: 1, isActive: true, deletedAt: null, createdAt: new Date(), updatedAt: new Date() },
  sport: null,
  images: [],
  variants: [],
  ...overrides,
});
