/** Major cities across India for venue search & forms */
export const INDIAN_CITIES = [
  'Agartala',
  'Agra',
  'Ahmedabad',
  'Aizawl',
  'Ajmer',
  'Akola',
  'Alappuzha',
  'Aligarh',
  'Allahabad',
  'Alwar',
  'Ambala',
  'Amravati',
  'Amritsar',
  'Anand',
  'Anantapur',
  'Asansol',
  'Aurangabad',
  'Ayodhya',
  'Bangalore',
  'Bareilly',
  'Belagavi',
  'Bengaluru',
  'Berhampur',
  'Bhagalpur',
  'Bharuch',
  'Bhavnagar',
  'Bhilai',
  'Bhiwandi',
  'Bhopal',
  'Bhubaneswar',
  'Bikaner',
  'Bilaspur',
  'Chandigarh',
  'Chennai',
  'Coimbatore',
  'Cuttack',
  'Darbhanga',
  'Davangere',
  'Dehradun',
  'Delhi',
  'Dhanbad',
  'Dhule',
  'Dibrugarh',
  'Dimapur',
  'Durgapur',
  'Erode',
  'Faridabad',
  'Gandhinagar',
  'Gangtok',
  'Gaya',
  'Ghaziabad',
  'Goa',
  'Gorakhpur',
  'Greater Noida',
  'Gulbarga',
  'Guntur',
  'Gurugram',
  'Guwahati',
  'Gwalior',
  'Haldwani',
  'Haridwar',
  'Hisar',
  'Howrah',
  'Hubballi',
  'Hyderabad',
  'Imphal',
  'Indore',
  'Itanagar',
  'Jabalpur',
  'Jaipur',
  'Jalandhar',
  'Jammu',
  'Jamnagar',
  'Jamshedpur',
  'Jhansi',
  'Jodhpur',
  'Junagadh',
  'Kadapa',
  'Kakinada',
  'Kalyan',
  'Kanpur',
  'Karimnagar',
  'Karnal',
  'Kochi',
  'Kohima',
  'Kolhapur',
  'Kolkata',
  'Kollam',
  'Kota',
  'Kottayam',
  'Kozhikode',
  'Kurnool',
  'Lucknow',
  'Ludhiana',
  'Madurai',
  'Mangaluru',
  'Mathura',
  'Meerut',
  'Moradabad',
  'Mumbai',
  'Muzaffarpur',
  'Mysuru',
  'Nagpur',
  'Nashik',
  'Navi Mumbai',
  'Nellore',
  'Noida',
  'Panaji',
  'Panipat',
  'Patiala',
  'Patna',
  'Pondicherry',
  'Pune',
  'Raipur',
  'Rajahmundry',
  'Rajkot',
  'Ranchi',
  'Rourkela',
  'Saharanpur',
  'Salem',
  'Secunderabad',
  'Shimla',
  'Shillong',
  'Siliguri',
  'Solapur',
  'Srinagar',
  'Surat',
  'Thane',
  'Thiruvananthapuram',
  'Thrissur',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tirupati',
  'Tiruppur',
  'Udaipur',
  'Ujjain',
  'Vadodara',
  'Varanasi',
  'Vasai',
  'Vellore',
  'Vijayawada',
  'Visakhapatnam',
  'Warangal',
] as const;

export type IndianCity = (typeof INDIAN_CITIES)[number];

/** Featured cities shown on marketing surfaces */
export const POPULAR_CITIES = [
  'Bangalore',
  'Mumbai',
  'Delhi',
  'Hyderabad',
  'Chennai',
  'Pune',
  'Kolkata',
  'Kochi',
  'Ahmedabad',
  'Jaipur',
  'Chandigarh',
  'Indore',
] as const;

export function filterIndianCities(query: string, limit = 80): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...INDIAN_CITIES];
  const starts: string[] = [];
  const includes: string[] = [];
  for (const city of INDIAN_CITIES) {
    const lower = city.toLowerCase();
    if (lower.startsWith(q)) starts.push(city);
    else if (lower.includes(q)) includes.push(city);
  }
  return [...starts, ...includes].slice(0, limit);
}
